# dataset
dataset_root_path : "..\\dataset"
text_list : ["PS1",
             "PS2",
             "PS3",
             "PS4",
             "PS5",
             "PS6",
             "EPS1",
             "FS1",
             "FS2",
             "TS1",
             "TS2",
             "TS3",
             "TS4",
             "VS1",
             "SE",
             "CE",
             "CP",
             "profile"]
save_path : "..\\processed_data\\data_dict.pkl"
save_lda_path : "..\\processed_data\\data_after_lda.pkl"
save_pca_path : "..\\processed_data\\data_after_pca.pkl"
save_standard_pca_path : "..\\processed_data\\standard_data_after_pca.pkl"
save_augment_root : "..\\processed_data"
augment_ num : 100
dataset_augment_num : 100
shots_num : 5

# attribute information
information : [[3, 20, 100], [100, 90, 80, 73], [0, 1, 2], [130, 115, 100, 90]]

# logs
save_log_path : "..\\experiments\\logs\\concat_linear3_with_standard_data.log"

# model_path
save_model_root_path : "..\\experiments\\models"

# diffusion_parameters
num_diffusion_steps : 3000
beta_start : 0.0001
beta_end : 0.02

# train_parameters
checkpoint_interval : 10
epochs : 600
batch_size : 512
learning_rate : 1e-3
device : 'cpu'
