# dataset
dataset_root_path : "..\\dataset"
text_list : ["PS1",
             "PS2",
             "PS3",
             "PS4",
             "PS5",
             "PS6",
             "EPS1",
             "FS1",
             "FS2",
             "TS1",
             "TS2",
             "TS3",
             "TS4",
             "VS1",
             "SE",
             "CE",
             "CP",
             "profile"]
save_path : "..\\processed_data\\data_dict.pkl"
save_lda_path : "..\\processed_data\\data_after_lda.pkl"
save_pca_path : "..\\processed_data\\data_after_pca.pkl"
save_standard_pca_path : "..\\processed_data\\standard_data_after_pca.pkl"
save_lda_standard_path : "..\\processed_data\\save_lda_standard.pkl"
save_standard_split_pca_path : "..\\processed_data\\save_standard_split_pca.pkl"
save_split_lda_standard_path : "..\\processed_data\\save_split_lda_standard.pkl"
save_split_standard_pca_dim3_path: "..\\processed_data\\save_standard_split_pca_dim3.pkl"
save_split_lda_standard_dim3_path: "..\\processed_data\\save_split_lda_standard_dim3.pkl"
augment_data_root : "..\\processed_data\\test\\augment"
tep_train_path : "..\\processed_data\\tep_train.pkl"
#tep_train_lda_standard_path : "processed_data\\tep_train_lda_standard.pkl"
tep_train_lda_standard_path : "processed_data\\tep_train_lda_zscore_standard.pkl"

#classifier_path : "experiments\\models\\classifier\\classifier.pkl"
classifier_path : "experiments\\models\\classifier\\classifier_zscore.pkl"
classifier_scale : 5

#log
diffusion_root : "experiments\\logs\\test\\diffusion"
augment_root : "experiments\\logs\\test\\augment"
classification_root : "experiments\\logs\\test\\classification"

save_data_root : "..\\processed_data"
augment_num : 20
dataset_augment_num : 100
shots_num : 9
ways_num : 5

# attribute information
information : [[3, 20, 100], [100, 90, 80, 73], [0, 1, 2], [130, 115, 100, 90]]
#method : 'LDA'
method : 'LDA Standard'

# logs
save_log_path : "..\\experiments\\logs\\concat_linear3_with_split.log"

# model_path
save_model_root_path : "..\\experiments\\models"

# diffusion_parameters
num_diffusion_steps : 50
beta_start : 0.00001
beta_end : 0.005
schedule_name : 'linear'

# train_parameters
checkpoint_interval : 10
epochs : 2000
batch_size : 512
learning_rate : 5e-4
device : 'cuda'

dataset_type : 'TEP'
