# path
dataset_root_path : "..\\dataset"
text_list : ["PS1",
             "PS2",
             "PS3",
             "PS4",
             "PS5",
             "PS6",
             "EPS1",
             "FS1",
             "FS2",
             "TS1",
             "TS2",
             "TS3",
             "TS4",
             "VS1",
             "SE",
             "CE",
             "CP",
             "profile"]
save_path : "..\\processed_data\\data_dict.pkl"
save_lda_path : "..\\processed_data\\data_after_lda.pkl"
# attribute information
information : [[3, 20, 100], [100, 90, 80, 73], [0, 1, 2], [130, 115, 100, 90]]