# path
data :
  save_lda_path: "processed_data\\data_after_lda.pkl"
  save_pca_path: "processed_data\\data_after_pca.pkl"
  save_standard_pca_path: "processed_data\\standard_data_after_pca.pkl"
  save_split_standard_pca_path: "processed_data\\save_standard_split_pca.pkl"
  save_split_standard_pca_dim3_path: "processed_data\\save_standard_split_pca_dim3.pkl"
  save_lda_standard_path : "processed_data\\save_lda_zscore_standard.pkl"
  save_split_lda_standard_path : "processed_data\\save_split_lda_standard.pkl"
  save_split_lda_standard_dim3_path: "processed_data\\save_split_lda_standard_dim3.pkl"
  tep_train_path : "processed_data\\tep_train.pkl"
#  tep_train_lda_standard_path : "processed_data\\tep_train_lda_standard.pkl"
  tep_train_lda_standard_path : "processed_data\\tep_train_lda_zscore_standard.pkl"
augment :
#  lda_root : "..\\processed_data\\test\\lda_augment"
#  pca_root : "..\\processed_data\\test\\pca_augment"
#  split_standard_pca_root : "..\\processed_data\\test\\split_standard_pca_augment"
#  standard_pca_root : "..\\processed_data\\test\\standard_pca_augment"
  augment_data_root : "processed_data\\test\\augment"
diffusion_model :
  root : "experiments\\models\\test"
classification_model :
  root : "experiments\\classifications\\test"
log :
  diffusion_root : "experiments\\logs\\test\\diffusion"
  augment_root : "experiments\\logs\\test\\augment"
  classification_root : "experiments\\logs\\test\\classification"

classifier:
#  classifier_path : "experiments\\models\\classifier\\classifier.pkl"
  classifier_path : "experiments\\models\\classifier\\Hydraulic_classifier_zscore.pkl"
  classifier_scale : 5

# shots num and ways num
shots_num : [1, 3, 5, 7, 9, 11]
ways_num : 5

# attribute information
information : [[3, 20, 100], [100, 90, 80, 73], [0, 1, 2], [130, 115, 100, 90]]

# method
#methods : ['Split Standard Dim3 PCA']
methods : ['LDA Standard']

# diffusion_parameters
diffusion_parameters :
  num_diffusion_steps : 50
  beta_start : 0.00001
  beta_end : 0.005
  schedule_name : 'linear'

# train_parameters
train_parameters :
  checkpoint_interval : 10
  epochs : 2000
  batch_size : 32
  learning_rate : 1e-3
  device : 'cuda'

#augment_num : 20
augment_num : 60
dataset_type : 'Hydraulic'